name: mypets_app
description: "MyPets_App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^3.0.0
  iconsax: ^0.0.8
  carousel_slider: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  mysql1: ^0.20.0
  pin_code_fields: ^7.3.0
  fluttertoast: ^8.0.7
  image: ^3.0.1
  http: ^0.13.3
  logger: ^2.0.2+1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  barcode_scanner: ^3.6.2
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  flutter_date_pickers: ^0.4.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - android/assets/images/

fonts:
  - family: GemunuLibre
    fonts:
      - asset: android/assets/images/fonts/GemunuLibre-Bold.ttf

  - family: Abel
    fonts:
      - asset: android/assets/images/fonts/Abel-Regular.ttf
        weight: 700
